### PR TITLE
Add light variant

### PR DESCRIPTION
**Pull request by fabjan**
I love a nice monochrome syntax hilighter theme, but I also like switching to a light theme during the day. Yours was the only proper monochrome theme I could find. And instead of making my own light whatever theme I thought I could share this back to you instead. So here is my suggestion for a light version of your theme.

Note: I reverted the terminal ANSI colors because I wanted to see which they were before making them monochrome again. What do you think each of the ANSI colors should be in a light version of the theme?

Preview (looks like my nerd font is broken in that terminal, oh well):

Skärmavbild 2024-05-10 kl  22 11 29

### CODE REVIEW

**Comment by fabjan** [comment]
I tried now setting all the base ANSI colors to #55555 and the bright ones to #aaaaa (and black and white to full black and white). I guess this makes sense, but it's not going to catch programs using other colors.

For example: I use https://the.exa.website/ instead of ls in interactive shells and with

```
COLORTERM=truecolor
TERM=xterm-256color
```

it uses a lot of colors that appear to not be targetable with a Zed theme:

Skärmavbild 2024-05-10 kl  22 48 32

**Review by borngraced — COMMENTED** [review]
great work and thank you very much for this PR..I'v been too lazy to do it myself. thank you

did you take a look at this for inspiration? The current dark version was greatly inspire by it's dark version!
https://github.com/pgdouyon/vim-yin-yang/blob/master/colors/yang.vim

**Comment by fabjan** [comment]
Oh, I'll take a look at that for sure.

(There was no great intentionality in my approach. I think I mainly copy pasted colors from your dark variant and then fudged it by eye trying to make it look decent inverted)

How similar do you think your color choices are to the yin version? Did you add any new ones or was it more of a port over to the Zed theming context (so you had to remap some colors and map new names to some already in the palette)?

**Comment by fabjan** [comment]
I went through the yang palette to adjust all my colors to it.

I did not try and remap the vim syntax nodes to Zed syntax nodes, and I chose a default background one notch darker than `#f7f7f7` which in my opinion is unnecessarily bright.

Skärmavbild 2024-05-11 kl  12 38 08

Still kept the ANSI terminal colors as colors (somewhat because the 256 color terminals not actually letting you control that anyway). If you want I can apply the color mapping from that yang version. Here is how it compares in my Zed terminal to keeping the standard EGA colors:

Skärmavbild 2024-05-11 kl  12 50 04
Skärmavbild 2024-05-11 kl  12 50 19

Here are some examples of colors it cannot capture (why I was hesitant to even try those sixteen colors):

Skärmavbild 2024-05-11 kl  12 51 56

But perhaps they are rare enough to warrant the remapping. It's your theme so I will let you decide!

**Comment by borngraced** [comment]
Nice, it's looking good @fabjan.
Screenshot 2024-05-11 at 17 10 38


what about replacing blue, green, and with solid bold and darker black? so we won't have other colors and if you must use other colors, you should consider `gruvbox yellow` `#d7991` for the active file in the explorer.

what do you think?

**Comment by fabjan** [comment]
IIRC, these are the only colors I left in:

For diff stuff (for example the colors of files in the file tree if git tracks them):
* conflict
* created
* modified
* deleted

For notices and squgglies:
* error
* warning

Aside from that I left all 16 ANSI colors in color. These are the ones I then showed screenshots of what they could look like if we make them monochrome.

> what about replacing blue, green, and other rgb colors with solid bold and darker black

Do you mean these sixteen terminal ANSI colors? All solid bold black? Or only some of them? Do you think I should greyscale them like in my suggested screenshot (same ANSI color mapping as the yang theme you linked as far as I can tell)?

Or do you mean to replace the blue and green git change colors showing up in the file tree?

As far as I can tell, there is no way to replace just any RGB colors in the terminal, just the sixteen ANSI ones.

**Comment by borngraced** [comment]
ok let's do this then as the main goal of the theme is to be able to utilize black and white as much as possible
image


>  As far as I can tell, there is no way to replace just any RGB colors in the terminal, just the sixteen ANSI ones.

yes, I'm aware

**Comment by borngraced** [comment]
nits: @fabjan don't forget to add your name to the authors list and also rename the dark version to `Monosami Dark`, currently it's showing `Monosami` and `Monosami Light`

**Comment by fabjan** [comment]
The ANSI colors are no more! And the previous dark theme got a new name.

I also added a screenshot, and bumped the extension version, and added myself to "authors".

**Review by borngraced — APPROVED** [review]
LGTM!!! thanks for the huge contribution.

**Pull request merged**
